services:
  postgres:
    image: 'postgres:latest'
    container_name: meatDB
    environment:
      - 'POSTGRES_DB=meatDB'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
